### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by WaddlesADuck** [DanielJones02/Echo#1]
I got this error when i ran the windows .bat file

Traceback (most recent call last):
  File "C:\Users\veera\Downloads\Echo\src\main.py", line 6, in <module>
    from utilities import *
  File "C:\Users\veera\Downloads\Echo\src\utilities.py", line 2, in <module>
    from discord.ext import commands
ModuleNotFoundError: No module named 'discord'

**Comment by Daniel-191** [comment]
try the following command in command prompt: 

```pip install discord```

and run main.py or win_run.bat again

**Comment by WaddlesADuck** [comment]
It's still not working,
when it trys to install this package it fails

Collecting multidict==5.1.0
  Using cached multidict-5.1.0.tar.gz (53 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: multidict
  Building wheel for multidict (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for multidict (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [82 lines of output]
      *********************
      * Accelerated build *
      *********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\multidict
      copying multidict\_abc.py -> build\lib.win-amd64-cpython-312\multidict
      copying multidict\_compat.py -> build\lib.win-amd64-cpython-312\multidict
      copying multidict\_multidict_base.py -> build\lib.win-amd64-cpython-312\multidict
      copying multidict\_multidict_py.py -> build\lib.win-amd64-cpython-312\multidict
      copying multidict\__init__.py -> build\lib.win-amd64-cpython-312\multidict
      running egg_info
      writing multidict.egg-info\PKG-INFO
      writing dependency_links to multidict.egg-info\dependency_links.txt
      writing top-level names to multidict.egg-info\top_level.txt
      reading manifest file 'multidict.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files found matching 'multidict\_multidict.html'
      warning: no previously-included files found matching 'multidict\*.so'
      warning: no previously-included files found matching 'multidict\*.pyd'
      warning: no previously-included files found matching 'multidict\*.pyd'
      no previously-included directories found matching 'docs\_build'
      adding license file 'LICENSE'
      writing manifest file 'multidict.egg-info\SOURCES.txt'
      C:\Users\veera\AppData\Local\Temp\pip-build-env-vm_pkf07\overlay\Lib\site-packages\setuptools\command\build_py.py:207: _Warning: Package 'multidict._multilib' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'multidict._multilib' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'multidict._multilib' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'multidict._multilib' to be distributed and are
              already explicitly excluding 'multidict._multilib' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      copying multidict\__init__.pyi -> build\lib.win-amd64-cpython-312\multidict
      copying multidict\_multidict.c -> build\lib.win-amd64-cpython-312\multidict
      copying multidict\py.typed -> build\lib.win-amd64-cpython-312\multidict
      creating build\lib.win-amd64-cpython-312\multidict\_multilib
      copying multidict\_multilib\defs.h -> build\lib.win-amd64-cpython-312\multidict\_multilib
      copying multidict\_multilib\dict.h -> build\lib.win-amd64-cpython-312\multidict\_multilib
      copying multidict\_multilib\istr.h -> build\lib.win-amd64-cpython-312\multidict\_multilib
      copying multidict\_multilib\iter.h -> build\lib.win-amd64-cpython-312\multidict\_multilib
      copying multidict\_multilib\pair_list.h -> build\lib.win-amd64-cpython-312\multidict\_multilib
      copying multidict\_multilib\views.h -> build\lib.win-amd64-cpython-312\multidict\_multilib
      running build_ext
      building 'multidict._multidict' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for multidict
Failed to build multidict
ERROR: Could not build wheels for multidict, which is required to install pyproject.toml-based projects
Requirement already satisfied: async-timeout==3.0.1 in c:\users\veera\appdata\local\programs\python\python312\lib\site-packages (3.0.1)
Requirement already satisfied: chardet==4.0.0 in c:\users\veera\appdata\local\programs\python\python312\lib\site-packages (4.0.0)
Traceback (most recent call last):
  File "C:\Users\veera\Downloads\Echo-3.4.6\Echo-3.4.6\src\main.py", line 6, in <module>
    from utilities import *
  File "C:\Users\veera\Downloads\Echo-3.4.6\Echo-3.4.6\src\utilities.py", line 2, in <module>
    from discord.ext import commands
ModuleNotFoundError: No module named 'discord'

[process exited with code 1 (0x00000001)]
You can now close this terminal with Ctrl+D, or press Enter to restart.

**Comment by Daniel-191** [comment]
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]

**Comment by Daniel-191** [comment]
Try installing that
